### ISSUE TITLE
The test interactive_shell_define_fun_rec_multiline fails

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#11146]
**Describe the bug**
```
3716/3718 Test #3776: interactive_shell_define_fun_rec_multiline ...................................................***Failed    1.59 sec
Traceback (most recent call last):
  File "/usr/ports/math/cvc5/work/cvc5-cvc5-1.2.0/test/binary/interactive_shell_define_fun_rec_multiline.py", line 83, in <module>
    main()
  File "/usr/ports/math/cvc5/work/cvc5-cvc5-1.2.0/test/binary/interactive_shell_define_fun_rec_multiline.py", line 80, in main
    sys.exit(check_iteractive_shell_define_fun_rec_multiline())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/ports/math/cvc5/work/cvc5-cvc5-1.2.0/test/binary/interactive_shell_define_fun_rec_multiline.py", line 46, in check_iteractive_shell_define_fun_rec_multiline
    expect_exact(child, "... > ")
  File "/usr/ports/math/cvc5/work/cvc5-cvc5-1.2.0/test/binary/interactive_shell_define_fun_rec_multiline.py", line 25, in expect_exact
    child.expect_exact(s)
  File "/usr/local/lib/python3.11/site-packages/pexpect/spawnbase.py", line 432, in expect_exact
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x344cbd3d4d0>
command: bin/cvc5
args: ['bin/cvc5']
buffer (last 100 chars): b'cvc5> '
before (last 100 chars): b'(error "Parse Error: <shell>:1.16: Expected SMT-LIBv2 symbol, got `` (EOF_TOK).")\r\ncvc5> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 62322
child_fd: 6
closed: False
timeout: 1
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: b'... > '

```

**cvc5 version/commit**: 1.2.0
**Operating system**: FreeBSD 14.1

**Comment by daniel-larraz** [comment]
This is the same problem as #10414, but it fails on FreeBSD.
