### ISSUE TITLE
Python/SWIG: SIGSEGV when dealing with unsat core

### ISSUE THREAD

**Issue by andrewvaughanj** [cvc5/cvc5#3088]
I have been working on the following branch [python_tests](https://github.com/CVC4/CVC4/compare/master...andrewvaughanj:python_tests) to:

- Translate the Java tests into Python tests

- Translate the Java API examples into Python API examples

- Allow for the Python tests and API examples to be runnable via CMake (`ctest -R PythonTest` and `ctest -R PythonExamples` respectively).

As part of this, I have found a segmentation violation while translating [`UnsatCores.java`](https://github.com/CVC4/CVC4/blob/master/examples/api/java/UnsatCores.java).

```
class UnsatCores(object):
    def __init__(self):
        self.em = CVC4.ExprManager()
        self.smt = CVC4.SmtEngine(self.em)

    def main(self):
        # Enable the production of unsat cores
        self.smt.setOption("produce-unsat-cores", CVC4.SExpr(True))

        boolType = self.em.booleanType()
        a = self.em.mkVar("A", boolType)
        b = self.em.mkVar("B", boolType)

        # A ^ B
        self.smt.assertFormula(self.em.mkExpr(CVC4.AND, a, b))
        # ~(A v B)
        self.smt.assertFormula(
            self.em.mkExpr(CVC4.NOT, self.em.mkExpr(CVC4.OR, a, b))
        )

        res = self.smt.checkSat()  # result is unsat

        # Retrieve the unsat core
        unsatCore = self.smt.getUnsatCore()

        # Print the unsat core
        print("Unsat Core: " + str(unsatCore))

        # Iterate over expressions in the unsat core. The `UnsatCore` class
        # implements the `Iterable<Expr>` interface.
        print("--- Unsat Core ---")
        exprs = unsatCore.begin()
        for expr in exprs:
            print(expr.toString())


if __name__ == "__main__":
    UnsatCores().main()
```

When you run this, you get the following output:

```
Unsat Core: <CVC4.UnsatCore; proxy of <Swig Object of type 'CVC4::UnsatCore *' at 0x7fdb6770a420> >
--- Unsat Core ---
NOT(A OR B)
A AND B
Segmentation fault
```

Inspecting this in `gdb`, the crash looks like this:

```
#0  CVC4::ExprManager::getNodeManager (this=0x211) at /home/avj/cvc4_testing/src/CVC4_avj/src/expr/expr_manager_template.cpp:1020
#1  0x00007fffef5c92d1 in CVC4::ExprManagerScope::ExprManagerScope (e=..., this=<synthetic pointer>)
    at /home/avj/cvc4_testing/src/CVC4_avj/src/./expr/expr_manager_scope.h:55
#2  CVC4::Expr::Expr (this=0x9627e0, e=...) at /home/avj/cvc4_testing/src/CVC4_avj/src/expr/expr_template.cpp:139
#3  0x00007ffff00a7b7c in swig::traits_from<CVC4::Expr>::from (val=...)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:4066
#4  swig::from<CVC4::Expr> (val=...) at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:4085
#5  swig::from_oper<CVC4::Expr>::operator() (this=<optimized out>, v=...)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:4649
#6  swig::SwigPyIteratorOpen_T<__gnu_cxx::__normal_iterator<CVC4::Expr const*, std::vector<CVC4::Expr, std::allocator<CVC4::Expr> > >, CVC4::Expr, swig::from_oper<CVC4::Expr> >::value (this=<optimized out>)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:4671
#7  0x00007fffeff9ea86 in swig::SwigPyIterator::next (this=0x91fea0)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:3474
#8  swig::SwigPyIterator::__next__ (this=0x91fea0)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:3483
#9  _wrap_SwigPyIterator___next__ (args=<optimized out>)
    at /home/avj/cvc4_testing/src/CVC4_avj/build/src/bindings/python/CMakeFiles/_CVC4.dir/cvc4PYTHON_wrap.cxx:7184
```

If there are any suggestions on how to start to further debug and diagnose this issue, then I am more than happy to take a look.

**Comment by mpreiner** [comment]
I'll close this issue since the Python/SWIG bindings don't exist anymore.
