### ISSUE TITLE
Segfault in CVC4::api::Term::~Term()

### ISSUE THREAD

**Issue by KevOrr** [cvc5/cvc5#5329]
**Describe the bug**
The destructor for `Term` sometimes causes segfaults. For some reason, triggering a python traceback (by using the old `e.isConst()` method) causes a segfault when the GC cleans up when python is exiting.

Traceback:
```
#0  0x00007ffff4f93dc0 in CVC4::ExprManager::getNodeManager() const () from /home/kevin/src/CVC4/build/src/libcvc4.so.7
#1  0x00007ffff404788a in CVC4::api::Term::~Term() () from /home/kevin/src/CVC4/build/src/libcvc4.so.7
#2  0x00007ffff5410cc2 in __pyx_tp_dealloc_6pycvc4_Term(_object*) () from /home/kevin/.pyenv/versions/3.8.2/envs/test/lib/python3.8/site-packages/pycvc4/pyc#3  0x00005555555f2105 in _Py_DECREF (filename=<synthetic pointer>, lineno=541, op=<optimized out>) at ./Include/object.h:478
#4  _Py_XDECREF (op=<optimized out>) at ./Include/object.h:541
#5  free_keys_object (keys=0x7ffff0f5b750) at Objects/dictobject.c:584
#6  0x00005555555f4609 in dictkeys_decref (dk=<optimized out>) at Objects/dictobject.c:324
#7  PyDict_Clear (op=<optimized out>) at Objects/dictobject.c:1729
#8  0x00007ffff0f4b950 in ?? ()
#9  0x00005555556d953c in delete_garbage (state=<optimized out>, state=<optimized out>, old=0x5555558dda00 <_PyRuntime+416>, collectable=0x7fffffffd700) at Mo#10 collect (generation=generation@entry=2, n_collected=n_collected@entry=0x7fffffffd808, n_uncollectable=n_uncollectable@entry=0x7fffffffd810, nofail=nofail@#11 0x00005555556da0d9 in collect_with_callback (state=<optimized out>, generation=2) at Modules/gcmodule.c:1240
#12 PyGC_Collect () at Modules/gcmodule.c:1833
#13 PyGC_Collect () at Modules/gcmodule.c:1817
#14 _PyGC_CollectIfEnabled () at Modules/gcmodule.c:1844
#15 0x00005555556b1389 in Py_FinalizeEx () at Python/pylifecycle.c:1223
#16 0x00005555556b2b95 in Py_FinalizeEx () at Python/pylifecycle.c:1159
#17 0x00005555555bc0b0 in Py_RunMain () at Modules/main.c:646
#18 pymain_main (args=0x7fffffffd860) at Modules/main.c:674
#19 Py_BytesMain (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:698
#20 0x00007ffff7c43152 in __libc_start_main () from /usr/lib/libc.so.6
#21 0x00005555555bad4e in _start () at Objects/dictobject.c:904
```

Here's a minimal test:
```py
import pycvc4

def test_1():
    slv = pycvc4.Solver()
    x = slv.mkReal(0)
    print(x.isConst())

def test_2():
    slv = pycvc4.Solver()
    x = slv.mkReal(0)
    print(x.isConst())

def test_3():
    slv = pycvc4.Solver()
    x = slv.mkReal(0)
    print(x.isConst())
```
Run it with pytest. The weird thing is how sporadic it is. In my actual tests for example, `isConst` needs to be called twice before a segfault occurs; here, it needs to be called three times.

**Command line arguments**: using the python bindings

**CVC4 version/commit**: 
Oldest I tested was a6817647ee9bae0df0f1922c0d521d7f100d0245 (when the api changed, which started causing the tracebacks in the first place), and it seems to still be in master (098cee0ea412e24e24caa79307e2950a640279af)

**Operating system**: `Linux 5.8.13-arch1-1 x86_64 GNU/Linux`

**`configure.sh` options**: `./configure.sh --python-bindings --python3 --ninja`

<details>
  <summary><b><code>configure.sh</code> output</b></summary>

```
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building Production build
-- Performing Test HAVE_FLAG_O3
-- Performing Test HAVE_FLAG_O3 - Success
-- Configuring with C flag '-O3'
-- Configuring with CXX flag '-O3'
-- Performing Test HAVE_FLAG_Wall
-- Performing Test HAVE_FLAG_Wall - Success
-- Configuring with C flag '-Wall'
-- Configuring with CXX flag '-Wall'
-- Performing Test HAVE_FLAG_fexceptions
-- Performing Test HAVE_FLAG_fexceptions - Success
-- Configuring with C flag '-fexceptions'
-- Performing Test HAVE_FLAG_Wno_deprecated
-- Performing Test HAVE_FLAG_Wno_deprecated - Success
-- Configuring with C flag '-Wno-deprecated'
-- Configuring with CXX flag '-Wno-deprecated'
-- Performing Test HAVE_FLAG_Wsuggest_override
-- Performing Test HAVE_FLAG_Wsuggest_override - Success
-- Configuring with CXX flag '-Wsuggest-override'
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor
-- Performing Test HAVE_FLAG_Wnon_virtual_dtor - Success
-- Configuring with CXX flag '-Wnon-virtual-dtor'
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough
-- Performing Test HAVE_FLAG_Wimplicit_fallthrough - Success
-- Configuring with C flag '-Wimplicit-fallthrough'
-- Configuring with CXX flag '-Wimplicit-fallthrough'
-- Performing Test HAVE_FLAG_Wshadow
-- Performing Test HAVE_FLAG_Wshadow - Success
-- Configuring with C flag '-Wshadow'
-- Configuring with CXX flag '-Wshadow'
-- Performing Test HAVE_FLAG_Wno_class_memaccess
-- Performing Test HAVE_FLAG_Wno_class_memaccess - Success
-- Configuring with CXX flag '-Wno-class-memaccess'
-- Using GNU gold linker.
CMake Warning at CMakeLists.txt:292 (message):
  Disabling unit tests since assertions are disabled.


-- Found PythonInterp: /home/kevin/.pyenv/shims/python3 (found suitable version "3.8.2", minimum required is "3") 
-- Found GMP: /usr/include  
-- Found GMP libs: /usr/lib/libgmp.so
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS
-- Performing Test CVC4_NEED_INT64_T_OVERLOADS - Failed
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD
-- Performing Test CVC4_NEED_HASH_UINT64_T_OVERLOAD - Failed
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for C++ include ext/stdio_filebuf.h
-- Looking for C++ include ext/stdio_filebuf.h - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for ffs
-- Looking for ffs - found
-- Looking for optreset
-- Looking for optreset - not found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Looking for strerror_r
-- Looking for strerror_r - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Performing Test STRERROR_R_CHAR_P
-- Performing Test STRERROR_R_CHAR_P - Failed
-- Found Git: /usr/bin/git (found version "2.28.0") 
-- Looking for antlr3FileStreamNew
-- Looking for antlr3FileStreamNew - found
-- Found ANTLR: /home/kevin/src/CVC4.copy/deps/install/bin/antlr3  
-- Found ANTLR libs: /home/kevin/src/CVC4.copy/deps/install/lib/libantlr3c.a
-- Found Java: /usr/bin/java (found version "11.0.8") found components: Runtime 
-- Found PythonInterp: /home/kevin/.pyenv/shims/python3 (found version "3.8.2") 
-- Found PythonLibs: /usr/lib/libpython3.8.so (found version "3.8.6") 
-- Found Cython: /home/kevin/.pyenv/shims/cython (Required is at least version "0.29") 
Python bindings install command: /home/kevin/.pyenv/shims/python3 /home/kevin/src/CVC4.copy/build/src/api/python/setup.py install
CVC4 1.9-prerelease

Build profile             : production

GPL                       : off
Best configuration        : off
Optimization level        : off

Assertions                : off
Debug symbols             : off
Debug context mem mgr     : off

Dumping                   : on
Muzzle                    : off
Proofs                    : on
Statistics                : on
Tracing                   : off

ASan                      : off
UBSan                     : off
TSan                      : off
Coverage (gcov)           : off
Profiling (gprof)         : off
Unit tests                : off
Valgrind                  : off

Shared libs               : on
Static binary             : off
Python bindings           : on
Java bindings             : off
Python2                   : off
Python3                   : on

ABC                       : off
CaDiCaL                   : off
CryptoMiniSat             : off
drat2er                   : off
GLPK                      : off
Kissat                    : off
LFSC                      : off
LibPoly                   : off

BUILD_LIB_ONLY            : off
MP library                : gmp
Editline                  : off
SymFPU                    : off


CPPLAGS (-D...)           : NDEBUG CVC4_DUMPING CVC4_PROOF CVC4_STATISTICS_ON
CXXFLAGS                  : -O3 -Wall -Wno-deprecated -Wsuggest-override -Wnon-virtual-dtor -Wimplicit-fallthrough -Wshadow -Wno-class-memaccess
CFLAGS                    : -O3 -Wall -fexceptions -Wno-deprecated -Wimplicit-fallthrough -Wshadow
Linker flags              :  -fuse-ld=gold

Install prefix            : /usr/local

CVC4 license              : modified BSD

Note that this configuration is NOT built against any GPL'ed libraries, so
it is covered by the (modified) BSD license.  This is, however, not the best
performing configuration of CVC4.  To build against GPL'ed libraries which
improve CVC4's performance, re-configure with '-DENABLE_GPL -DENABLE_BEST'.

Now change to 'build' and type 'ninja', followed by 'ninja check' or 'ninja install'.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/kevin/src/CVC4.copy/build
```
</details>

**Comment by 4tXJ7f** [comment]
@KevOrr Thank you very much for your report. This is a great find. After some debugging, I believe that the issue is as follows: The traceback object causes a reference cycle (I am a little fuzzy on _what_ exactly the cycle is but the [Python docs](https://devguide.python.org/garbage_collector/#identifying-reference-cycles) claims that traceback objects are often involved in cycles) and when everything is cleaned up, `tp_clear()` gets called on `Term` due to the cycle, which in turn causes the `Solver` to be deallocated before the deconstructor of `Term` is called (see the [Cython docs](https://cython.readthedocs.io/en/latest/src/userguide/extension_types.html#disabling-cycle-breaking-tp-clear)). A fix that seems to do the trick for me is adding `@cython.no_gc_clear` as a decorator for `Term` and other classes that hold a reference to `Solver` (requires the `import` of `cython`) in cvc4.pxi. Could you please test if that works for you?

**Comment by nafur** [comment]
A whole lot has changed in the Python API since this issues was opened (and we don't even export `isConst()` anymore). Given that we have pretty extensive tests now that seem to be stable: can you still reproduce this or a similar issue with the released API?

**Comment by KevOrr** [comment]
I haven't used the python API in a long time but I'm good with closing this for those reasons
