### ISSUE TITLE
(produce-abducts) Fatal failure at src/theory/eager_proof_generator.cpp:35 

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#6605]
Commit: 0e9fed3
OS: Ubuntu 18.04

```
[532] % cvc4-1.8 -q --check-unsat-cores small.smt2
(define-fun d () Bool (= b a))
[533] % cvc5 -q --check-unsat-cores small.smt2
Fatal failure within void cvc5::theory::EagerProofGenerator::setProofFor(cvc5::Node, std::shared_ptr<cvc5::ProofNode>) at /local/suz-local/software/CVC4/src/theory/eager_proof_generator.cpp:35
Check failure

 pf->getResult() == f
EagerProofGenerator::setProofFor: unexpected result
Expected: (>= rsk_11 1)
Actual: (not (not (>= rsk_11 1)))

Aborted
[534] % 
[534] % cat small.smt2
(set-option :produce-abducts true)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(assert (= (>= b c) (>= 0 a)))
(assert (= c a))
(get-abduct d (<= a b))
[535] % 
```

**Comment by rainoftime** [comment]
**src/smt/abduction_solver.cpp:108**
~~~~
(get-abduct A true)
~~~~
cvc5  -q -i --produce-abducts delta.out.smt2 
Fatal failure within bool cvc5::smt::AbductionSolver::getAbductInternal(cvc5::Node&) at /home/cvc5/src/smt/abduction_solver.cpp:108
Check failure

 !agdtbv.isNull()

Aborted
~~~~

**Comment by rainoftime** [comment]
**src/theory/uf/equality_engine.cpp:585**
~~~~
(declare-sort S0 0)
(declare-sort S2 0)
(declare-fun arr0 () (Array Bool S2))
(declare-fun arr1 () (Array S2 (Array S0 (Array S0 (Array S0 Bool)))))
(declare-fun arr2 () (Array Bool (Array Bool (Array S0 (Array S0 (Array S0 Bool))))))
(get-abduct A (= (select (select arr2 false) true) (select arr1 (select arr0 false))))
~~~~
~~~~
cvc5 -q --produce-abducts x.smt2 
Fatal failure within cvc5::TNode cvc5::theory::eq::EqualityEngine::getRepresentative(cvc5::TNode) const at /home/cvc5/src/theory/uf/equality_engine.cpp:585
Check failure

 hasTerm(t)

Aborted
~~~~

**Comment by ajreynol** [comment]
Last one appears to be specific to arrays solver:
```
#0  0x000000000135da95 in raise ()
#1  0x000000000040494d in abort ()
#2  0x00000000008b74ca in cvc5::FatalStream::~FatalStream (this=this@entry=0x7fffffffb5ff, __in_chrg=<optimized out>) at /space/ajreynol/cvc5-ajr/src/base/check.cpp:32
#3  0x000000000074ddd5 in cvc5::theory::eq::EqualityEngine::getRepresentative (this=this@entry=0x1f55c88, t=...) at /space/ajreynol/cvc5-ajr/src/theory/uf/equality_engine.cpp:587
#4  0x000000000053d3fd in cvc5::theory::arrays::TheoryArrays::mergeArrays (this=this@entry=0x1f55120, a=..., b=...)
    at /space/ajreynol/cvc5-ajr/src/theory/arrays/theory_arrays.cpp:1563
#5  0x000000000054fab6 in cvc5::theory::arrays::TheoryArrays::NotifyClass::eqNotifyMerge (this=this@entry=0x1f56370, t1=..., t2=...)
    at /space/ajreynol/cvc5-ajr/src/./theory/arrays/theory_arrays.h:341
#6  0x000000000075a2a4 in cvc5::theory::eq::EqualityEngine::merge (this=this@entry=0x204c5c0, class1=..., class2=..., triggersFired=...)
    at /space/ajreynol/cvc5-ajr/src/theory/uf/equality_engine.cpp:744
```
