### ISSUE TITLE
(finite-model-finder) Assertion error at src/theory/type_enumerator.cpp:88

### ISSUE THREAD

**Issue by rainoftime** [cvc5/cvc5#6690]
Hi, for the following formula, cvc5 7608747
~~~~
(set-option :finite-model-find true)
(assert (forall ((a String)) (forall ((b String)) (str.in_re a (re.++ re.allchar (str.to_re b))))))
(check-sat)

cvc5 -q -i --check-models delta.out.smt2
Fatal failure within static cvc5::theory::TypeEnumeratorInterface* cvc5::theory::TypeEnumerator::mkTypeEnumerator(cvc5::TypeNode, cvc5::theory::TypeEnumeratorProperties*) at /home//cvc5/build/src/theory/type_enumerator.cpp:88
Unhandled case encounteredNo type enumerator for type `RegLan'
Aborted (core dumped)
~~~~

**Comment by nafur** [comment]
I just noted that you are apparently using pyDelta to minimize the smtlib files. Thank you for doing this, minimizing the inputs before opening the issue helps debugging it very much.
You might want to consider switching to ddSMT: it has seen major improvements recently and is usually superior to pyDelta now. Development on pyDelta will not continue and all relevant techniques from pyDelta have been incorporated into ddSMT.
See https://ddsmt.readthedocs.io/en/master/index.html for documentation on ddSMT.

**Comment by rainoftime** [comment]
Thanks for the information! I will try the new version of ddSMT.

**Comment by rainoftime** [comment]
**Segfault at src/util/dlist.h:45**
~~~~
(declare-const x38 Bool)
(declare-const x4 Bool)
(set-option :sat.branching.heuristic chb)
(declare-datatypes ((P 0)) (((P))))
(declare-datatypes ((N 0)) ((x3 y)))
(declare-datatypes ((A 0)) (((a) (c (p P)))))
(declare-fun G (N P Int) Bool)
(declare-fun g (N Int Int) A)
(assert x38)
(assert (= x4 (forall ((x N) (t Int)) (or (not x4) (G x3 (p (g x3 t 0)) 0) (not ((_ is c) (g x t 0))) (forall ((x N) (y N) (t Int)) (or (not ((_ is c) (g x t 0))) (not ((_ is c) (g y 0 0)))))))))
(check-sat)
~~~~
~~~~
AddressSanitizer:DEADLYSIGNAL
=================================================================
==76818==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000023fd894 bp 0x7ffdc9f56a30 sp 0x7ffdc9f56980 T0)
==76818==The signal is caused by a READ memory access.
==76818==Hint: address points to the zero page.
    #0 0x23fd894 in dll_base<q::binding>::remove_from(q::binding*&, q::binding*) /home/z3-debug/build/../src/util/dlist.h:45:19
    #1 0x23fef0c in q::ematch::remove_binding::undo() /home/z3-debug/build/../src/sat/smt/q_ematch.cpp:199:13
    #2 0xfacf4f in undo_trail_stack(ptr_vector<trail>&, unsigned int) /home/z3-debug/build/../src/util/trail.h:388:16
    #3 0xfacdea in trail_stack::pop_scope(unsigned int) /home/z3-debug/build/../src/util/trail.h:421:9
    #4 0xfa7290 in trail_stack::reset() /home/z3-debug/build/../src/util/trail.h:401:9
    #5 0x2193233 in euf::solver::~solver() /home/z3-debug/build/../src/sat/smt/euf_solver.h:212:21
    #6 0x3920630 in void deallocf<sat::extension>(char const*, int, sat::extension*) /home/z3-debug/build/../src/util/memory_manager.h:85:11
    #7 0x390f39b in scoped_ptr<sat::extension>::operator=(sat::extension*) /home/z3-debug/build/../src/util/util.h:266:13
    #8 0x38ac42e in sat::solver::~solver() /home/z3-debug/build/../src/sat/sat_solver.cpp:93:15
    #9 0x2140500 in void deallocf<sat::solver_core>(char const*, int, sat::solver_core*) /home/z3-debug/build/../src/util/memory_manager.h:85:11
    #10 0x2140458 in scoped_ptr<sat::solver_core>::~scoped_ptr() /home/z3-debug/build/../src/util/util.h:241:9
    #11 0x21403a7 in sat_tactic::imp::~imp() /home/z3-debug/build/../src/sat/tactic/sat_tactic.cpp:28:12
    #12 0x213cbad in sat_tactic::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) /home/z3-debug/build/../src/sat/tactic/sat_tactic.cpp:227:5
    #13 0x2d0f996 in cleanup_tactical::operator()(ref<goal> const&, sref_buffer<goal, 16u>&) /home/z3
~~~~
