### ISSUE TITLE
FP example fails with assertion failure in SymFPU.

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5#7368]
`example/api/floating_pointarith` fails with the following assertion failure in SymFPU:
```
a = (fp #b1 #b11111111 #b00000000000000000000000)
b = (fp #b0 #b11111111 #b00000000000000000000000)
c = (fp #b0 #b00000000 #b00000000000000000000000)
a = (fp #b0 #b11111111 #b00000000000000000000000)
b = (fp #b1 #b11111111 #b00000000000000000000000)
c = (fp #b0 #b00000000 #b00000000000000000000000)
d = (fp #b1 #b10010000 #b00000000000000000000000) = (- 131072.0)
((_ fp.to_sbv 16) RTP d) = Fatal failure within static void cvc5::symfpuLiteral::traits::precondition(const prop&) at /cvc5/src/util/floatingpoint_literal_symfpu_traits.cpp:399
Check failure

 p

Aborted (core dumped)
```
Here's the stack trace:
```
2  0x00007ffff78b644e in cvc5::FatalStream::~FatalStream() () from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
#3  0x00007ffff77f8eab in cvc5::symfpuLiteral::traits::precondition(bool const&) () from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
#4  0x00007ffff77eb135 in cvc5::symfpuLiteral::wrappedBitVector<true> symfpu::conditionalNegate<cvc5::symfpuLiteral::traits, cvc5::symfpuLiteral::wrappedBitVector<true>, bool>(bool const&, cvc5::symfpuLiteral::wrappedBitVector<true> const&) () from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
#5  0x00007ffff77e7d51 in cvc5::FloatingPointLiteral::convertToSBVTotal(cvc5::BitVectorSize, cvc5::RoundingMode const&, cvc5::BitVector) const ()
   from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
#6  0x00007ffff77e336e in cvc5::FloatingPoint::convertToBVTotal(cvc5::BitVectorSize, cvc5::RoundingMode const&, bool, cvc5::BitVector) const ()
   from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
#7  0x00007ffff6f77cb9 in cvc5::theory::fp::constantFold::convertToSBVTotal(cvc5::NodeTemplate<false>, bool) () from /home/an/git/dev/nafur-cvc5-fork/build/install/lib/libcvc5.so.1
<snip>
```
And here's a smaller example that fails:
```
(set-logic ALL)
(set-option :produce-models true)
(set-option :check-models true)
(declare-const d Float32)
(assert (distinct ((_ fp.to_sbv 4) RTP d) ((_ fp.to_sbv 4) RTN d)))
(check-sat)
```

**cvc5 version/commit**: https://github.com/cvc5/cvc5/commit/215519d099aee88bf53bddc71f071382484d29c0

**`configure.sh` options**  
`debug --auto-download`

**Comment by zhendongsu** [comment]
Another example:
```
[532] % cvc5 -q --check-models small.smt2 
Fatal failure within static void cvc5::symfpuLiteral::traits::precondition(const prop&) at /local/suz-local/software/CVC4/src/util/floatingpoint_literal_symfpu_traits.cpp:399
Check failure

 p

Aborted
[533] % cat small.smt2 
(declare-const x Float64)
(assert (distinct (_ bv0 32) (bvlshr ((_ extract 31 0) ((_ sign_extend 32) ((_ fp.to_sbv 32) RTZ x))) (_ bv0 32))))
(check-sat)
```

**Comment by aniemetz** [comment]
This is fixed on main as of b1f01ab90b05cbc2e1f152e179012d1b200c5fb5 with MPFR as a back end (still fails with SymFPU).
