### ISSUE TITLE
Memory leak on a simple formula

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8773]
Hi,
For this simple instance, cvc5 https://github.com/cvc5/cvc5/commit/c8b193f93369e042bf768d8ba567d6dc4ba01e7e throws a leak.
This may be related to #8767.
```
$ cat simple.smt2
(assert (= 0.0 (sin 7)))
(check-sat)
$ cvc5 -q simple.smt2
(error "Subexpressions must have the same type:
Equation: (= 7 (+ SKOLEM_FUN_TRANSCENDENTAL_PURIFY_ARG_2 (* 2.0 s_3 real.pi)))
Type 1: Int
Type 2: Real
")

=================================================================
==10318==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4971b3a808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f49700bc5a7 in cvc5::internal::NodeBuilder::constructNV() /root/cvc5/src/expr/node_builder.cpp:491
    #2 0x7f49700bdb79 in cvc5::internal::NodeBuilder::constructNode() /root/cvc5/src/expr/node_builder.cpp:365
    #3 0x7f496df06ab0 in cvc5::internal::NodeManager::mkNode(cvc5::internal::kind::Kind_t, cvc5::internal::NodeTemplate<false>, cvc5::internal::NodeTemplate<false>) /root/cvc5/build/src/expr/node_manager.h:1132
    #4 0x7f496ea70a53 in cvc5::internal::theory::arith::nl::transcendental::SineSolver::getPhaseShiftLemma(cvc5::internal::NodeTemplate<true> const&, cvc5::internal::NodeTemplate<true> const&, cvc5::internal::NodeTemplate<true> const&) /root/cvc5/src/theory/arith/nl/transcendental/sine_solver.cpp:154
    #5 0x7f496ea72c50 in cvc5::internal::theory::arith::nl::transcendental::SineSolver::doPhaseShift(cvc5::internal::NodeTemplate<false>, cvc5::internal::NodeTemplate<false>) /root/cvc5/src/theory/arith/nl/transcendental/sine_solver.cpp:194
    #6 0x7f496ea924e2 in cvc5::internal::theory::arith::nl::transcendental::TranscendentalSolver::initLastCall(std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/theory/arith/nl/transcendental/transcendental_solver.cpp:90
    #7 0x7f496ea16a14 in cvc5::internal::theory::arith::nl::NonlinearExtension::runStrategy(cvc5::internal::theory::Theory::Effort, std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&, std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&, std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/theory/arith/nl/nonlinear_extension.cpp:490
    #8 0x7f496ea1d41a in cvc5::internal::theory::arith::nl::NonlinearExtension::modelBasedRefinement(std::set<cvc5::internal::NodeTemplate<true>, std::less<cvc5::internal::NodeTemplate<true> >, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/theory/arith/nl/nonlinear_extension.cpp:346
    #9 0x7f496ea1fd66 in cvc5::internal::theory::arith::nl::NonlinearExtension::checkFullEffort(std::map<cvc5::internal::NodeTemplate<true>, cvc5::internal::NodeTemplate<true>, std::less<cvc5::internal::NodeTemplate<true> >, std::allocator<std::pair<cvc5::internal::NodeTemplate<true> const, cvc5::internal::NodeTemplate<true> > > >&, std::set<cvc5::internal::NodeTemplate<true>, std::less<cvc5::internal::NodeTemplate<true> >, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/theory/arith/nl/nonlinear_extension.cpp:273
    #10 0x7f496eaf7005 in cvc5::internal::theory::arith::TheoryArith::postCheck(cvc5::internal::theory::Theory::Effort) /root/cvc5/src/theory/arith/theory_arith.cpp:246
    #11 0x7f496fe3ba21 in cvc5::internal::theory::Theory::check(cvc5::internal::theory::Theory::Effort) /root/cvc5/src/theory/theory.cpp:633
    #12 0x7f496fe53eca in cvc5::internal::TheoryEngine::check(cvc5::internal::theory::Theory::Effort) /root/cvc5/src/theory/theory_engine.cpp:437
    #13 0x7f496e47a308 in cvc5::internal::prop::TheoryProxy::theoryCheck(cvc5::internal::theory::Theory::Effort) /root/cvc5/src/prop/theory_proxy.cpp:174
    #14 0x7f496e38ba66 in cvc5::internal::Minisat::Solver::theoryCheck(cvc5::internal::theory::Theory::Effort) /root/cvc5/src/prop/minisat/core/Solver.cc:1327
    #15 0x7f496e3afbce in cvc5::internal::Minisat::Solver::propagate(cvc5::internal::Minisat::Solver::TheoryCheckType) /root/cvc5/src/prop/minisat/core/Solver.cc:1215
    #16 0x7f496e3b07da in cvc5::internal::Minisat::Solver::search(int) /root/cvc5/src/prop/minisat/core/Solver.cc:1547
    #17 0x7f496e3b2fb6 in cvc5::internal::Minisat::Solver::solve_() /root/cvc5/src/prop/minisat/core/Solver.cc:1808
    #18 0x7f496e3da408 in cvc5::internal::Minisat::SimpSolver::solve_(bool, bool) /root/cvc5/src/prop/minisat/simp/SimpSolver.cc:149
    #19 0x7f496e3cc965 in cvc5::internal::Minisat::SimpSolver::solve(bool, bool) /root/cvc5/src/./prop/minisat/simp/SimpSolver.h:228
    #20 0x7f496e3c8922 in cvc5::internal::prop::MinisatSatSolver::solve() /root/cvc5/src/prop/minisat/minisat.cpp:199
    #21 0x7f496e43216c in cvc5::internal::prop::PropEngine::checkSat() /root/cvc5/src/prop/prop_engine.cpp:406
    #22 0x7f496e5a8643 in cvc5::internal::smt::SmtSolver::checkSatisfiability(cvc5::internal::smt::Assertions&, std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/smt/smt_solver.cpp:152
    #23 0x7f496e589715 in cvc5::internal::SolverEngine::checkSatInternal(std::vector<cvc5::internal::NodeTemplate<true>, std::allocator<cvc5::internal::NodeTemplate<true> > > const&) /root/cvc5/src/smt/solver_engine.cpp:766
    #24 0x7f496e58a6a4 in cvc5::internal::SolverEngine::checkSat(cvc5::internal::NodeTemplate<true> const&) /root/cvc5/src/smt/solver_engine.cpp:742
    #25 0x7f496e58a87d in cvc5::internal::SolverEngine::checkSat() /root/cvc5/src/smt/solver_engine.cpp:731
    #26 0x7f496de76577 in cvc5::Solver::checkSat() const /root/cvc5/src/api/cpp/cvc5.cpp:6315
    #27 0x7f496e4a98a0 in cvc5::CheckSatCommand::invoke(cvc5::Solver*, cvc5::SymbolManager*) /root/cvc5/src/smt/command.cpp:438
    #28 0x7f496e497e94 in cvc5::Command::invoke(cvc5::Solver*, cvc5::SymbolManager*, std::ostream&) /root/cvc5/src/smt/command.cpp:209
    #29 0x55ca9b0d8c2c in cvc5::main::solverInvoke(cvc5::Solver*, cvc5::SymbolManager*, cvc5::Command*, std::ostream&) /root/cvc5/src/main/command_executor.cpp:211
......
SUMMARY: AddressSanitizer: 232 byte(s) leaked in 10 allocation(s).
```

**Comment by 4tXJ7f** [comment]
With newer versions of Clang and GCC (tested on both Linux and macOS), I cannot reproduce the memory leak on commit c8b193f93369e042bf768d8ba567d6dc4ba01e7e. Given that the typing issue has also been fixed, I am closing this issue for now. @merlinsun please feel free to reopen the issue if I am missing something.
