### ISSUE TITLE
(--sygus-inst) Fatal failure within void cvc5::internal::NodeBuilder::realloc(size_t) at src/expr/node_builder.cpp:278

### ISSUE THREAD

**Issue by KJongUk** [cvc5/cvc5#8913]
Hi,
For this formula:
[small.txt](https://github.com/cvc5/cvc5/files/8989286/small.txt)
(Sorry,  I tried to minimize smt-lib file possible using ddsmt. But it was still large..)
cvc5  3f63a768eb2405b246a35e1386ca742f87691585 
<pre>
<code>
$ cvc5 --sygus-inst -q small.smt2
Fatal failure within void cvc5::internal::NodeBuilder::realloc(size_t) at ./cvc5/src/expr/node_builder.cpp:278
Check failure

 toSize > d_nvMaxChildren
attempt to realloc() a NodeBuilder to a smaller/equal size!
Aborted
</code>
</pre>

**Comment by ajreynol** [comment]
Backtrace:
```
Program received signal SIGABRT, Aborted.
0x0000000001388fab in __pthread_kill_implementation.constprop.0 ()
#0  0x0000000001388fab in __pthread_kill_implementation.constprop.0 ()
#1  0x0000000001363c46 in gsignal ()
#2  0x0000000000404fe1 in abort ()
#3  0x0000000000842420 in cvc5::internal::FatalStream::~FatalStream (this=this@entry=0x7fffffffa2bc, __in_chrg=<optimized out>) at /space/ajreynol/cvc5-ajr/src/base/check.cpp:32
#4  0x000000000074c55c in cvc5::internal::NodeBuilder::realloc (this=<optimized out>, toSize=<optimized out>) at /space/ajreynol/cvc5-ajr/src/expr/node_builder.cpp:278
#5  0x000000000074c922 in cvc5::internal::NodeBuilder::realloc (this=this@entry=0x7fffffffa3c0) at /space/ajreynol/cvc5-ajr/src/expr/node_builder.cpp:656
#6  0x000000000074c945 in cvc5::internal::NodeBuilder::allocateNvIfNecessaryForAppend (this=this@entry=0x7fffffffa3c0) at /space/ajreynol/cvc5-ajr/src/expr/node_builder.cpp:663
#7  0x000000000074e8d9 in cvc5::internal::NodeBuilder::append (this=this@entry=0x7fffffffa3c0, n=...) at /space/ajreynol/cvc5-ajr/src/expr/node_builder.cpp:255
#8  0x000000000053d829 in cvc5::internal::NodeBuilder::append<__gnu_cxx::__normal_iterator<cvc5::internal::NodeTemplate<false> const*, std::vector<cvc5::internal::NodeTemplate<false>, std::allocator<cvc5::internal::NodeTemplate<false> > > > > (this=this@entry=0x7fffffffa3c0, begin=..., end=...) at /space/ajreynol/cvc5-ajr/src/./expr/node_builder.h:248
#9  0x000000000053d965 in cvc5::internal::NodeBuilder::append<false> (this=this@entry=0x7fffffffa3c0, children=...) at /space/ajreynol/cvc5-ajr/src/./expr/node_builder.h:238
#10 0x000000000053d990 in cvc5::internal::NodeManager::mkNode<false> (this=<optimized out>, kind=<optimized out>, children=...) at /dev/shm/ajreynol/cmake/ajr/debug/src/expr/node_manager.h:1120
#11 0x000000000092325e in cvc5::internal::expr::algorithm::flatten<>(cvc5::internal::NodeTemplate<false>) (t=...) at /space/ajreynol/cvc5-ajr/src/./expr/algorithm/flatten.h:116
#12 0x000000000091f241 in cvc5::internal::theory::arith::ArithRewriter::preRewritePlus (t=...) at /space/ajreynol/cvc5-ajr/src/theory/arith/arith_rewriter.cpp:425
#13 0x000000000091f491 in cvc5::internal::theory::arith::ArithRewriter::preRewriteTerm (t=...) at /space/ajreynol/cvc5-ajr/src/theory/arith/arith_rewriter.cpp:226
#14 0x000000000091f992 in cvc5::internal::theory::arith::ArithRewriter::preRewrite (this=this@entry=0x1be5458, t=...) at /space/ajreynol/cvc5-ajr/src/theory/arith/arith_rewriter.cpp:60
#15 0x000000000062aa8b in cvc5::internal::theory::Rewriter::preRewrite (this=this@entry=0x1b9e840, theoryId=<optimized out>, n=..., tcpg=tcpg@entry=0x0) at /space/ajreynol/cvc5-ajr/src/theory/rewriter.cpp:427
#16 0x000000000062c914 in cvc5::internal::theory::Rewriter::rewriteTo (this=this@entry=0x1b9e840, theoryId=<optimized out>, node=..., tcpg=tcpg@entry=0x0) at /space/ajreynol/cvc5-ajr/src/theory/rewriter.cpp:210
#17 0x000000000062ea81 in cvc5::internal::theory::Rewriter::rewrite (this=this@entry=0x1b9e840, node=...) at /space/ajreynol/cvc5-ajr/src/theory/rewriter.cpp:96
#18 0x0000000000d14ba2 in cvc5::internal::theory::SubstitutionMap::apply (this=this@entry=0x1e428c0, t=..., r=r@entry=0x1b9e840, tracker=tracker@entry=0x0, stc=stc@entry=0x0) at /space/ajreynol/cvc5-ajr/src/theory/substitutions.cpp:238
#19 0x00000000006ec524 in cvc5::internal::theory::TrustSubstitutionMap::applyTrusted (this=this@entry=0x1e428b0, n=..., r=r@entry=0x1b9e840) at /space/ajreynol/cvc5-ajr/src/theory/trust_substitutions.cpp:152
#20 0x0000000001090ee5 in cvc5::internal::preprocessing::passes::NonClausalSimp::applyInternal (this=0x1dd6390, assertionsToPreprocess=0x1baf390) at /space/ajreynol/cvc5-ajr/src/preprocessing/passes/non_clausal_simp.cpp:310
#21 0x0000000000d78a48 in cvc5::internal::preprocessing::PreprocessingPass::apply (this=0x1dd6390, assertionsToPreprocess=assertionsToPreprocess@entry=0x1baf390) at /space/ajreynol/cvc5-ajr/src/preprocessing/preprocessing_pass.cpp:34
#22 0x00000000008eaa33 in cvc5::internal::smt::ProcessAssertions::applyPass (this=this@entry=0x1bafe80, pname=..., as=...) at /space/ajreynol/cvc5-ajr/src/smt/process_assertions.cpp:502
#23 0x00000000008eab9c in cvc5::internal::smt::ProcessAssertions::simplifyAssertions (this=this@entry=0x1bafe80, as=...) at /space/ajreynol/cvc5-ajr/src/smt/process_assertions.cpp:374
#24 0x00000000008ec340 in cvc5::internal::smt::ProcessAssertions::apply (this=this@entry=0x1bafe80, as=...) at /space/ajreynol/cvc5-ajr/src/smt/process_assertions.cpp:269
#25 0x00000000008e4cb1 in cvc5::internal::smt::Preprocessor::process (this=this@entry=0x1bafc00, as=...) at /space/ajreynol/cvc5-ajr/src/smt/preprocessor.cpp:81
#26 0x00000000004ea6b9 in cvc5::internal::smt::SmtSolver::processAssertions (this=this@entry=0x1bafbf0, as=...) at /space/ajreynol/cvc5-ajr/src/smt/smt_solver.cpp:225
#27 0x00000000004eacf4 in cvc5::internal::smt::SmtSolver::checkSatisfiability (this=0x1bafbf0, as=..., assumptions=...) at /space/ajreynol/cvc5-ajr/src/smt/smt_solver.cpp:145
#28 0x00000000004dbc54 in cvc5::internal::SolverEngine::checkSatInternal (this=this@entry=0x1b90900, assumptions=...) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:781
#29 0x00000000004dc0eb in cvc5::internal::SolverEngine::checkSat (this=this@entry=0x1b90900, assumption=...) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:757
#30 0x00000000004dc157 in cvc5::internal::SolverEngine::checkSat (this=0x1b90900) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:746
#31 0x000000000046919d in cvc5::Solver::checkSat (this=this@entry=0x1b6e3b0) at /space/ajreynol/cvc5-ajr/src/api/cpp/cvc5.cpp:6242
#32 0x00000000004c9bbc in cvc5::CheckSatCommand::invoke (this=0x1defbb0, solver=0x1b6e3b0, sm=<optimized out>) at /space/ajreynol/cvc5-ajr/src/smt/command.cpp:377
#33 0x00000000004c53dd in cvc5::Command::invoke (this=0x1defbb0, solver=0x1b6e3b0, sm=<optimized out>, out=...) at /space/ajreynol/cvc5-ajr/src/smt/command.cpp:164
#34 0x0000000000408cdc in cvc5::main::solverInvoke (solver=0x1b6e3b0, sm=sm@entry=0x1bb6880, cmd=cmd@entry=0x1defbb0, out=...) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:211
#35 0x000000000040943e in cvc5::main::CommandExecutor::doCommandSingleton (this=0x1bafb40, cmd=0x1defbb0) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:118
#36 0x0000000000408ef5 in cvc5::main::CommandExecutor::doCommand (this=this@entry=0x1bafb40, cmd=0x1defbb0) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:106
#37 0x0000000000407d33 in cvc5::main::CommandExecutor::doCommand (this=0x1bafb40, cmd=...) at /space/ajreynol/cvc5-ajr/src/./main/command_executor.h:67
#38 0x000000000040d893 in cvc5::main::ExecutionContext::solveContinuous (this=this@entry=0x7fffffffd3d0, parser=0x1bbfb50, stopAtSetLogic=stopAtSetLogic@entry=false) at /space/ajreynol/cvc5-ajr/src/main/portfolio_driver.cpp:60
#39 0x00000000004143a0 in cvc5::main::PortfolioDriver::solve (this=this@entry=0x7fffffffd490, executor=...) at /space/ajreynol/cvc5-ajr/src/main/portfolio_driver.cpp:422
#40 0x0000000000406cc3 in runCvc5 (argc=argc@entry=3, argv=argv@entry=0x7fffffffd918, solver=...) at /space/ajreynol/cvc5-ajr/src/main/driver_unified.cpp:227
#41 0x00000000004084eb in main (argc=3, argv=0x7fffffffd918) at /space/ajreynol/cvc5-ajr/src/main/main.cpp:35
```
