### ISSUE TITLE
Fatal failure when generating LFSC proof (ProofNodeManager::mkScope)

### ISSUE THREAD

**Issue by daniel-larraz** [cvc5/cvc5#9205]
**Describe the bug**
Running `cvc5 --lang=smt2 --dump-proofs --proof-format=lfsc --proof-granularity=theory-rewrite` on 
[lfsc_proof2.txt](https://github.com/cvc5/cvc5/files/9727704/lfsc_proof2.txt) fails with this error:
```
unsat
Fatal failure within std::shared_ptr<cvc5::internal::ProofNode> cvc5::internal::ProofNodeManager::mkScope(std::shared_ptr<cvc5::internal::ProofNode>, std::vector<cvc5::internal::NodeTemplate<true> >&, bool, bool, cvc5::internal::Node) at /home/runner/work/cvc5/cvc5/src/proof/proof_node_manager.cpp:229
Unreachable code reached Generated a proof that is not closed by the scope: 
Free assumption: (= (bvadd (top.res.2.call_22_3 1) [...]
Use -t dump-proof-error for details on proof

Aborted (core dumped)
```
**Command line arguments**: --lang=smt2 --dump-proofs --proof-format=lfsc --proof-granularity=theory-rewrite
**cvc5 version/commit**: cvc5-Linux-2022-10-05-6b8341e
**Operating system**: Ubuntu 20.04

**Comment by ajreynol** [comment]
I can reproduce and will look into the issue. Note this is independent of `--proof-format=lfsc`.

**Comment by ajreynol** [comment]
Using `--proof-check=eager`, the issue appears to be in equality proof conversion. The eq_proof converter is adding a MACRO_PRED_TRANSFORMATION step that does not hold, from here: https://github.com/cvc5/cvc5/blob/main/src/theory/uf/eq_proof.cpp#L1461.

**Comment by ajreynol** [comment]
Error/backtrace adding `--proof-check=eager`:
```
Fatal failure within cvc5::internal::Node cvc5::internal::ProofChecker::check(cvc5::internal::PfRule, const std::vector<std::shared_ptr<cvc5::internal::ProofNode> >&, const std::vector<cvc5::internal::NodeTemplate<true> >&, cvc5::internal::Node) at /space/ajreynol/cvc5-ajr/src/proof/proof_checker.cpp:105
Unreachable code reached ProofChecker::check: failed, result does not match expected value.
    PfRule: MACRO_SR_PRED_TRANSFORM
     child: (= (bvadd (bvadd (top.res.2.call_22_3 1) (top.res.2.call_22_2 1)) (bvadd (top.res.2.call_22_1 1) (top.res.2.call_22_0 1))) (bvadd (bvadd (top.res.2.call_22_3 0) (top.res.2.call_22_2 0)) (bvadd (top.res.2.call_22_1 0) (top.res.2.call_22_0 0))))
       arg: (= (bvadd (top.res.2.call_22_3 1) (bvadd (top.res.2.call_22_2 1) (bvadd (top.res.2.call_22_1 1) (top.res.2.call_22_0 1)))) (bvadd (top.res.2.call_22_3 0) (bvadd (top.res.2.call_22_2 0) (bvadd (top.res.2.call_22_1 0) (top.res.2.call_22_0 0)))))
    result: null
  expected: (= (bvadd (top.res.2.call_22_3 1) (bvadd (top.res.2.call_22_2 1) (bvadd (top.res.2.call_22_1 1) (top.res.2.call_22_0 1)))) (bvadd (top.res.2.call_22_3 0) (bvadd (top.res.2.call_22_2 0) (bvadd (top.res.2.call_22_1 0) (top.res.2.call_22_0 0)))))



Program received signal SIGABRT, Aborted.
0x00000000013c0b0b in __pthread_kill_implementation.constprop.0 ()
#0  0x00000000013c0b0b in __pthread_kill_implementation.constprop.0 ()
#1  0x000000000139b796 in gsignal ()
#2  0x0000000000404fe1 in abort ()
#3  0x000000000083fdd6 in cvc5::internal::FatalStream::~FatalStream (this=this@entry=0x7fffffff761f, __in_chrg=<optimized out>) at /space/ajreynol/cvc5-ajr/src/base/check.cpp:32
#4  0x000000000089cde0 in cvc5::internal::ProofChecker::check (this=this@entry=0x1c6ed30, id=<optimized out>, id@entry=cvc5::internal::PfRule::MACRO_SR_PRED_TRANSFORM, children=..., args=..., expected=...) at /space/ajreynol/cvc5-ajr/src/proof/proof_checker.cpp:105
#5  0x00000000008af658 in cvc5::internal::ProofNodeManager::checkInternal (this=this@entry=0x1c6edc0, id=cvc5::internal::PfRule::MACRO_SR_PRED_TRANSFORM, children=..., args=..., expected=..., didCheck=@0x7fffffff776f: false) at /space/ajreynol/cvc5-ajr/src/proof/proof_node_manager.cpp:339
#6  0x00000000008afba4 in cvc5::internal::ProofNodeManager::mkNode (this=this@entry=0x1c6edc0, id=<optimized out>, children=..., args=..., expected=...) at /space/ajreynol/cvc5-ajr/src/proof/proof_node_manager.cpp:50
#7  0x0000000000899b92 in cvc5::internal::CDProof::addStep (this=this@entry=0x7fffffffaa70, expected=..., id=<optimized out>, id@entry=cvc5::internal::PfRule::MACRO_SR_PRED_TRANSFORM, children=..., args=..., ensureChildren=<optimized out>, ensureChildren@entry=true, opolicy=<optimized out>) at /space/ajreynol/cvc5-ajr/src/proof/proof.cpp:201
#8  0x000000000072b99b in cvc5::internal::theory::eq::EqProof::addToProof (this=<optimized out>, p=0x7fffffffaa70, visited=..., assumptions=...) at /space/ajreynol/cvc5-ajr/src/theory/uf/eq_proof.cpp:1461
#9  0x00000000007282e8 in cvc5::internal::theory::eq::EqProof::addToProof (this=this@entry=0x3ff91d0, p=p@entry=0x7fffffffaa70, visited=..., assumptions=...) at /space/ajreynol/cvc5-ajr/src/theory/uf/eq_proof.cpp:1153
#10 0x000000000072df02 in cvc5::internal::theory::eq::EqProof::addToProof (this=0x3ff91d0, p=p@entry=0x7fffffffaa70) at /space/ajreynol/cvc5-ajr/src/theory/uf/eq_proof.cpp:794
#11 0x0000000000735541 in cvc5::internal::theory::eq::ProofEqEngine::explainWithProof (this=this@entry=0x1f93fc0, lit=..., assumps=..., curr=curr@entry=0x7fffffffaa70) at /space/ajreynol/cvc5-ajr/src/theory/uf/proof_equality_engine.cpp:551
#12 0x0000000000739234 in cvc5::internal::theory::eq::ProofEqEngine::explain (this=this@entry=0x1f93fc0, conc=...) at /space/ajreynol/cvc5-ajr/src/theory/uf/proof_equality_engine.cpp:295
#13 0x00000000006e0a43 in cvc5::internal::theory::TheoryInferenceManager::explainLit (this=this@entry=0x1cf4318, lit=...) at /space/ajreynol/cvc5-ajr/src/theory/theory_inference_manager.cpp:234
#14 0x0000000000a67039 in cvc5::internal::theory::bv::BVSolverBitblastInternal::explain (this=this@entry=0x1cee650, n=...) at /space/ajreynol/cvc5-ajr/src/theory/bv/bv_solver_bitblast_internal.cpp:155
#15 0x000000000053a852 in cvc5::internal::theory::bv::TheoryBV::explain (this=this@entry=0x1cf35e0, node=...) at /space/ajreynol/cvc5-ajr/src/theory/bv/theory_bv.cpp:338
#16 0x0000000000c21062 in cvc5::internal::theory::SharedSolverDistributed::explain (this=<optimized out>, literal=..., id=<optimized out>) at /space/ajreynol/cvc5-ajr/src/theory/shared_solver_distributed.cpp:83
#17 0x00000000006cb930 in cvc5::internal::TheoryEngine::getExplanation (this=this@entry=0x1cb4cf0, explanationVector=...) at /space/ajreynol/cvc5-ajr/src/theory/theory_engine.cpp:1636
#18 0x00000000006ce7e1 in cvc5::internal::TheoryEngine::getExplanation (this=this@entry=0x1cb4cf0, node=...) at /space/ajreynol/cvc5-ajr/src/theory/theory_engine.cpp:1170
#19 0x00000000008d3c4c in cvc5::internal::prop::TheoryProxy::explainPropagation (this=this@entry=0x1db8fe0, l=..., explanation=...) at /space/ajreynol/cvc5-ajr/src/prop/theory_proxy.cpp:204
#20 0x0000000000e07543 in cvc5::internal::Minisat::Solver::propagateTheory (this=this@entry=0x1de6e60) at /space/ajreynol/cvc5-ajr/src/prop/minisat/core/Solver.cc:1304
#21 0x0000000000e0771c in cvc5::internal::Minisat::Solver::propagate (this=this@entry=0x1de6e60, type=type@entry=cvc5::internal::Minisat::Solver::CHECK_WITH_THEORY) at /space/ajreynol/cvc5-ajr/src/prop/minisat/core/Solver.cc:1244
#22 0x0000000000e07a6a in cvc5::internal::Minisat::Solver::search (this=this@entry=0x1de6e60, nof_conflicts=<optimized out>) at /space/ajreynol/cvc5-ajr/src/prop/minisat/core/Solver.cc:1547
#23 0x0000000000e087ab in cvc5::internal::Minisat::Solver::solve_ (this=this@entry=0x1de6e60) at /space/ajreynol/cvc5-ajr/src/prop/minisat/core/Solver.cc:1808
#24 0x0000000000e14ea4 in cvc5::internal::Minisat::SimpSolver::solve_ (this=this@entry=0x1de6e60, do_simp=false, do_simp@entry=true, turn_off_simp=turn_off_simp@entry=false) at /space/ajreynol/cvc5-ajr/src/prop/minisat/simp/SimpSolver.cc:149
#25 0x0000000000e0ffc4 in cvc5::internal::Minisat::SimpSolver::solve (this=0x1de6e60, do_simp=do_simp@entry=true, turn_off_simp=turn_off_simp@entry=false) at /space/ajreynol/cvc5-ajr/src/./prop/minisat/simp/SimpSolver.h:228
#26 0x0000000000e0ec72 in cvc5::internal::prop::MinisatSatSolver::solve (this=0x1c6d9b0) at /space/ajreynol/cvc5-ajr/src/prop/minisat/minisat.cpp:199
#27 0x00000000008bd02c in cvc5::internal::prop::PropEngine::checkSat (this=0x1db3520) at /space/ajreynol/cvc5-ajr/src/prop/prop_engine.cpp:449
#28 0x00000000004e25d8 in cvc5::internal::smt::SmtSolver::checkSatInternal (this=0x1c3f170) at /space/ajreynol/cvc5-ajr/src/smt/smt_solver.cpp:119
#29 0x00000000004dfaf4 in cvc5::internal::smt::SmtDriverSingleCall::checkSatNext (this=0x1c6eca0) at /space/ajreynol/cvc5-ajr/src/smt/smt_driver.cpp:121
#30 0x00000000004dfe77 in cvc5::internal::smt::SmtDriver::checkSat (this=0x1c6eca0, assumptions=...) at /space/ajreynol/cvc5-ajr/src/smt/smt_driver.cpp:64
#31 0x00000000004d3d4c in cvc5::internal::SolverEngine::checkSatInternal (this=this@entry=0x1c24150, assumptions=...) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:732
#32 0x00000000004d40b0 in cvc5::internal::SolverEngine::checkSat (this=this@entry=0x1c24150, assumption=...) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:709
#33 0x00000000004d4103 in cvc5::internal::SolverEngine::checkSat (this=0x1c24150) at /space/ajreynol/cvc5-ajr/src/smt/solver_engine.cpp:699
#34 0x0000000000469c27 in cvc5::Solver::checkSat (this=this@entry=0x1c012c0) at /space/ajreynol/cvc5-ajr/src/api/cpp/cvc5.cpp:6335
#35 0x0000000001180c64 in cvc5::parser::CheckSatCommand::invoke (this=0x205fdf0, solver=0x1c012c0, sm=<optimized out>) at /space/ajreynol/cvc5-ajr/src/parser/api/cpp/command.cpp:398
#36 0x000000000117c64f in cvc5::parser::Command::invoke (this=0x205fdf0, solver=0x1c012c0, sm=<optimized out>, out=...) at /space/ajreynol/cvc5-ajr/src/parser/api/cpp/command.cpp:165
#37 0x0000000000408f6c in cvc5::main::solverInvoke (solver=0x1c012c0, sm=sm@entry=0x1c45fd0, cmd=cmd@entry=0x205fdf0, out=...) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:198
#38 0x0000000000409640 in cvc5::main::CommandExecutor::doCommandSingleton (this=0x1c3f0c0, cmd=0x205fdf0) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:105
#39 0x00000000004090fa in cvc5::main::CommandExecutor::doCommand (this=this@entry=0x1c3f0c0, cmd=0x205fdf0) at /space/ajreynol/cvc5-ajr/src/main/command_executor.cpp:94
#40 0x0000000000407ed9 in cvc5::main::CommandExecutor::doCommand (this=0x1c3f0c0, cmd=...) at /space/ajreynol/cvc5-ajr/src/./main/command_executor.h:69
#41 0x000000000040dcdf in cvc5::main::ExecutionContext::solveContinuous (this=this@entry=0x7fffffffd370, parser=0x1c4f610, stopAtSetLogic=stopAtSetLogic@entry=false) at /space/ajreynol/cvc5-ajr/src/main/portfolio_driver.cpp:61
#42 0x00000000004147ec in cvc5::main::PortfolioDriver::solve (this=this@entry=0x7fffffffd450, executor=...) at /space/ajreynol/cvc5-ajr/src/main/portfolio_driver.cpp:422
#43 0x0000000000406dc8 in runCvc5 (argc=argc@entry=6, argv=argv@entry=0x7fffffffd8c8, solver=...) at /space/ajreynol/cvc5-ajr/src/main/driver_unified.cpp:252
#44 0x000000000040877c in main (argc=6, argv=0x7fffffffd8c8) at /space/ajreynol/cvc5-ajr/src/main/main.cpp:35
