### ISSUE TITLE
Buffer over-read during parsing but only when input is streamed and not when read from a file

### ISSUE THREAD

**Issue by martin-cs** [cvc5/cvc5#9292]
**Describe the bug**
When file input is piped into `cvc5` valgrind detects a buffer over-read.  If the input is given a file this does not happen.  Sometimes (I would guess that it depends on the value read) this causes it to give a spurious and corrupted error message.

```
$ cat minimised.smt2
(set-info :smt-lib-version 2.6)
(set-logic FP)
(set-info :source |
Generated by: Mathias Preiner
Generated on: 2019-03-22
Application: Verification of floating-point invertibility conditions.
Target solver: CVC4, Z3
Publications: "Invertibility Conditions for Floating-Point Formulas" by M. Brain, A. Niemetz, M. Preiner, A. Reynolds, C. Barrett, and C. Tinelli, CAV 2019.
|)
(set-info :license "https://creativecommons.org/licenses/by/4.0/")
(set-info :category "crafted")
(check-sat)
(exit)

$  valgrind --tool=memcheck ./bin/cvc5 < ~/tmp/can-delete/minimised.smt2
==463810== Memcheck, a memory error detector
==463810== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==463810== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==463810== Command: ./bin/cvc5
==463810== 
==463810== Invalid read of size 2
==463810==    at 0x483F8A0: memmove (vg_replace_strmem.c:1270)
==463810==    by 0x48C75A5: symbol(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cvc5::parser::DeclarationCheck, cvc5::parser::SymbolType) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C7D92: simpleSymbolicExprNoKeyword(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C88F8: simpleSymbolicExpr(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C8EB0: symbolicExpr(Smt2Parser_Ctx_struct*, cvc5::Term&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C9879: setInfoInternal(Smt2Parser_Ctx_struct*, std::unique_ptr<cvc5::parser::Command, std::default_delete<cvc5::parser::Command> >*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E1EC0: command(Smt2Parser_Ctx_struct*, std::unique_ptr<cvc5::parser::Command, std::default_delete<cvc5::parser::Command> >*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E3583: parseCommand(Smt2Parser_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48923F1: cvc5::parser::Parser::nextCommand() (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x12B5BA: cvc5::main::ExecutionContext::solveContinuous(cvc5::parser::InputParser*, bool) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==    by 0x133DBE: cvc5::main::PortfolioDriver::solve(std::unique_ptr<cvc5::main::CommandExecutor, std::default_delete<cvc5::main::CommandExecutor> >&) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==    by 0x125D66: runCvc5(int, char**, std::unique_ptr<cvc5::Solver, std::default_delete<cvc5::Solver> >&) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==  Address 0x66563a4 is 0 bytes after a block of size 20 alloc'd
==463810==    at 0x483950F: operator new[](unsigned long) (vg_replace_malloc.c:431)
==463810==    by 0x4890B37: cvc5::parser::LineBuffer::readToLine(unsigned long) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x4890CC1: cvc5::parser::LineBuffer::getPtr(unsigned long, unsigned long) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FA9B: cvc5::parser::bufferedInputConsume(ANTLR3_INT_STREAM_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x4925FC1: antlr3dfapredict (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C3173: mTokens(Smt2Lexer_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488E10F: cvc5::parser::AntlrInput::nextTokenStr(ANTLR3_TOKEN_SOURCE_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488E1EB: cvc5::parser::AntlrInput::nextToken(ANTLR3_TOKEN_SOURCE_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FE3A: cvc5::parser::nextToken(cvc5::parser::BOUNDED_TOKEN_BUFFER_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FF17: cvc5::parser::tokLT(ANTLR3_TOKEN_STREAM_struct*, int) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FD6D: cvc5::parser::_LA(ANTLR3_INT_STREAM_struct*, int) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E3436: parseCommand(Smt2Parser_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810== 
==463810== Invalid read of size 2
==463810==    at 0x483F8AF: memmove (vg_replace_strmem.c:1270)
==463810==    by 0x48C75A5: symbol(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, cvc5::parser::DeclarationCheck, cvc5::parser::SymbolType) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C7D92: simpleSymbolicExprNoKeyword(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C88F8: simpleSymbolicExpr(Smt2Parser_Ctx_struct*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C8EB0: symbolicExpr(Smt2Parser_Ctx_struct*, cvc5::Term&) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C9879: setInfoInternal(Smt2Parser_Ctx_struct*, std::unique_ptr<cvc5::parser::Command, std::default_delete<cvc5::parser::Command> >*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E1EC0: command(Smt2Parser_Ctx_struct*, std::unique_ptr<cvc5::parser::Command, std::default_delete<cvc5::parser::Command> >*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E3583: parseCommand(Smt2Parser_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48923F1: cvc5::parser::Parser::nextCommand() (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x12B5BA: cvc5::main::ExecutionContext::solveContinuous(cvc5::parser::InputParser*, bool) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==    by 0x133DBE: cvc5::main::PortfolioDriver::solve(std::unique_ptr<cvc5::main::CommandExecutor, std::default_delete<cvc5::main::CommandExecutor> >&) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==    by 0x125D66: runCvc5(int, char**, std::unique_ptr<cvc5::Solver, std::default_delete<cvc5::Solver> >&) (in /home/city/working-copies/cvc5/build/bin/cvc5)
==463810==  Address 0x66563a6 is 2 bytes after a block of size 20 alloc'd
==463810==    at 0x483950F: operator new[](unsigned long) (vg_replace_malloc.c:431)
==463810==    by 0x4890B37: cvc5::parser::LineBuffer::readToLine(unsigned long) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x4890CC1: cvc5::parser::LineBuffer::getPtr(unsigned long, unsigned long) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FA9B: cvc5::parser::bufferedInputConsume(ANTLR3_INT_STREAM_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x4925FC1: antlr3dfapredict (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48C3173: mTokens(Smt2Lexer_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488E10F: cvc5::parser::AntlrInput::nextTokenStr(ANTLR3_TOKEN_SOURCE_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488E1EB: cvc5::parser::AntlrInput::nextToken(ANTLR3_TOKEN_SOURCE_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FE3A: cvc5::parser::nextToken(cvc5::parser::BOUNDED_TOKEN_BUFFER_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FF17: cvc5::parser::tokLT(ANTLR3_TOKEN_STREAM_struct*, int) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x488FD6D: cvc5::parser::_LA(ANTLR3_INT_STREAM_struct*, int) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810==    by 0x48E3436: parseCommand(Smt2Parser_Ctx_struct*) (in /home/city/working-copies/cvc5/build/src/parser/libcvc5parser.so.1)
==463810== 
sat
==463810== 
==463810== HEAP SUMMARY:
==463810==     in use at exit: 6,997,682 bytes in 4,366 blocks
==463810==   total heap usage: 7,892 allocs, 3,526 frees, 7,530,325 bytes allocated
==463810== 
==463810== LEAK SUMMARY:
==463810==    definitely lost: 0 bytes in 0 blocks
==463810==    indirectly lost: 0 bytes in 0 blocks
==463810==      possibly lost: 8 bytes in 1 blocks
==463810==    still reachable: 6,997,674 bytes in 4,365 blocks
==463810==                       of which reachable via heuristic:
==463810==                         multipleinheritance: 608 bytes in 2 blocks
==463810==         suppressed: 0 bytes in 0 blocks
==463810== Rerun with --leak-check=full to see details of leaked memory
==463810== 
==463810== For lists of detected and suppressed errors, rerun with: -s
==463810== ERROR SUMMARY: 1446 errors from 2 contexts (suppressed: 0 from 0)

$ valgrind --tool=memcheck ./bin/cvc5 ~/tmp/can-delete/minimised.smt2
==463818== Memcheck, a memory error detector
==463818== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==463818== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==463818== Command: ./bin/cvc5 /home/city/tmp/can-delete/minimised.smt2
==463818== 
sat
==463818== 
==463818== HEAP SUMMARY:
==463818==     in use at exit: 6,999,147 bytes in 4,372 blocks
==463818==   total heap usage: 7,882 allocs, 3,510 frees, 7,537,134 bytes allocated
==463818== 
==463818== LEAK SUMMARY:
==463818==    definitely lost: 0 bytes in 0 blocks
==463818==    indirectly lost: 0 bytes in 0 blocks
==463818==      possibly lost: 8 bytes in 1 blocks
==463818==    still reachable: 6,999,139 bytes in 4,371 blocks
==463818==                       of which reachable via heuristic:
==463818==                         multipleinheritance: 608 bytes in 2 blocks
==463818==         suppressed: 0 bytes in 0 blocks
==463818== Rerun with --leak-check=full to see details of leaked memory
==463818== 
==463818== For lists of detected and suppressed errors, rerun with: -s
==463818== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

**Command line arguments**: See above.
**cvc5 version/commit**: 661dab0fc0fd13b69efef1553b40689466befbe5
**Operating system**: Debian stable on x86_64

**Comment by martin-cs** [comment]
Update:
```
(set-info :source |
the line break is critical!|)
(check-sat)
```
is sufficient.  The line break is critical to triggering this which makes me think it is an off-by-one issue in handling line breaks when streaking in input.

**Comment by martin-cs** [comment]
I am reasonably sure it is the first line that triggers the problem and that the buffer length is fine.  I think for some reason new-line characters are counted in the length https://github.com/cvc5/cvc5/blob/d9eaadf8c476035146771fe34f659fc01d917656/src/parser/smt2/Smt2.g#L2094 but not put into the buffer leading to an over-read?

@4tXJ7f it looks like b78a3c17ab8fbf3fc1c0c294a4cc8fb9e9113108 touches this code, is it possible something got off-by-one'd?

**Comment by martin-cs** [comment]
b1289f90e0112cea1a164a259e3ac0e19c4b77cb does not have the error so it is b78a3c1 or later.

**Comment by martin-cs** [comment]
`b78a3c1` built with debug and `--asan` gives:

```
$ bin/cvc5 < ~/tmp/can-delete/minimised.smt2
=================================================================
==484178==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300002d354 at pc 0x7f30c2bd7983 bp 0x7ffe660a9cc0 sp 0x7ffe660a9470
READ of size 394 at 0x60300002d354 thread T0
    #0 0x7f30c2bd7982 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806
    #1 0x562ea7b811a2 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) /usr/include/c++/10/bits/basic_string.tcc:225
    #2 0x7f30c2836736 in cvc5::parser::AntlrInput::tokenText[abi:cxx11](ANTLR3_COMMON_TOKEN_struct*) /home/city/working-copies/cvc5/src/./parser/antlr_input.h:222
    #3 0x7f30c28ee6be in symbol /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:13505
    #4 0x7f30c28f1d34 in simpleSymbolicExprNoKeyword /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:8162
    #5 0x7f30c28f3119 in simpleSymbolicExpr /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:8374
    #6 0x7f30c28f3c00 in symbolicExpr /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:8513
    #7 0x7f30c28f535f in setInfoInternal /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:5545
    #8 0x7f30c2934683 in command /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:2727
    #9 0x7f30c293f601 in parseCommand /home/city/working-copies/cvc5/build/src/parser/smt2/Smt2Parser.cpp:2227
    #10 0x7f30c2891f51 in cvc5::parser::Smt2Input::parseCommand() /home/city/working-copies/cvc5/src/parser/smt2/smt2_input.cpp:63
    #11 0x7f30c284c958 in cvc5::parser::Parser::nextCommand() /home/city/working-copies/cvc5/src/parser/parser.cpp:662
    #12 0x562ea7b92641 in cvc5::main::ExecutionContext::solveContinuous(cvc5::parser::Parser*, bool) /home/city/working-copies/cvc5/src/main/portfolio_driver.cpp:58
    #13 0x562ea7ba2fd2 in cvc5::main::PortfolioDriver::solve(std::unique_ptr<cvc5::main::CommandExecutor, std::default_delete<cvc5::main::CommandExecutor> >&) /home/city/working-copies/cvc5/src/main/portfolio_driver.cpp:422
    #14 0x562ea7b7ee10 in runCvc5(int, char**, std::unique_ptr<cvc5::Solver, std::default_delete<cvc5::Solver> >&) /home/city/working-copies/cvc5/src/main/driver_unified.cpp:235
    #15 0x562ea7b82699 in main /home/city/working-copies/cvc5/src/main/main.cpp:35
    #16 0x7f30bd3f4d09 in __libc_start_main ../csu/libc-start.c:308
    #17 0x562ea7b7b899 in _start (/home/city/working-copies/cvc5/build/bin/cvc5+0x32899)

0x60300002d354 is located 0 bytes to the right of 20-byte region [0x60300002d340,0x60300002d354)
allocated by thread T0 here:
    #0 0x7f30c2c497a7 in operator new[](unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:102
    #1 0x7f30c283b7e7 in cvc5::parser::LineBuffer::readToLine(unsigned long) /home/city/working-copies/cvc5/src/parser/line_buffer.cpp:87
    #2 0x7f30c283bb21 in cvc5::parser::LineBuffer::getPtr(unsigned long, unsigned long) /home/city/working-copies/cvc5/src/parser/line_buffer.cpp:41
    #3 0x7f30c283777f in antlr3CreateLineBufferedStream /home/city/working-copies/cvc5/src/parser/antlr_line_buffered_input.cpp:408
    #4 0x7f30c2837923 in cvc5::parser::antlr3LineBufferedStreamNew(std::istream&, unsigned int, unsigned char*, cvc5::parser::LineBuffer*) /home/city/working-copies/cvc5/src/parser/antlr_line_buffered_input.cpp:330
    #5 0x7f30c282b255 in cvc5::parser::newAntlr3BufferedStream(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cvc5::parser::LineBuffer*) /home/city/working-copies/cvc5/src/parser/antlr_input.cpp:59
    #6 0x7f30c282b79d in cvc5::parser::AntlrInputStream::newStreamInputStream(std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/city/working-copies/cvc5/src/parser/antlr_input.cpp:143
    #7 0x7f30c283b28e in cvc5::parser::Input::newStreamInput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::istream&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/city/working-copies/cvc5/src/parser/input.cpp:65
    #8 0x562ea7b7ed54 in runCvc5(int, char**, std::unique_ptr<cvc5::Solver, std::default_delete<cvc5::Solver> >&) /home/city/working-copies/cvc5/src/main/driver_unified.cpp:225
    #9 0x562ea7b82699 in main /home/city/working-copies/cvc5/src/main/main.cpp:35
    #10 0x7f30bd3f4d09 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:806 in __interceptor_memcpy
Shadow bytes around the buggy address:
  0x0c067fffda10: fd fa fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c067fffda20: fd fd fd fa fa fa fd fd fd fa fa fa fd fd fd fa
  0x0c067fffda30: fa fa fd fd fd fa fa fa fd fd fd fd fa fa 00 00
  0x0c067fffda40: 00 07 fa fa fd fd fd fa fa fa fd fd fd fa fa fa
  0x0c067fffda50: fd fd fd fa fa fa 00 00 00 fa fa fa fd fd fd fd
=>0x0c067fffda60: fa fa fd fd fd fd fa fa 00 00[04]fa fa fa 00 00
  0x0c067fffda70: 00 00 fa fa 00 00 00 00 fa fa 00 00 00 fa fa fa
  0x0c067fffda80: 00 00 00 fa fa fa 00 00 00 fa fa fa 00 00 00 fa
  0x0c067fffda90: fa fa fd fd fd fd fa fa 00 00 00 06 fa fa fa fa
  0x0c067fffdaa0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c067fffdab0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==484178==ABORTING
```

**Comment by martin-cs** [comment]
The bug is present before so please ignore my speculation.

**Comment by ajreynol** [comment]
Can you try adding `--stdin-input-per-line` (after #9160)?

Also, I am in the process of rewriting the parser to avoid these issues altogether.

**Comment by martin-cs** [comment]
@ajreynol  confirmed that `--stdin-input-per-line` resolves the problem.

**Comment by ajreynol** [comment]
This is expected behavior then, we don't enable `--stdin-input-per-line` by default yet unfortunately since it degrades parsing performance fairly significantly.  This should all be resolved when we upgrade to a new parser.
