### ISSUE TITLE
Heap-buffer-overflow on a simple instance

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#9674]
Hi,
For this instance, cvc5 https://github.com/cvc5/cvc5/commit/7081f806f7492a257855dd3bc094f4470c25e595 debug build with `--asan`
```
$ cat delta.out.smt2 
(assert (fp (_ bv0 1)))
$ cvc5 delta.out.smt2 -q
=================================================================
==527821==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60300003a050 at pc 0x7f5760d27db2 bp 0x7ffe168fc6f0 sp 0x7ffe168fc6e0
READ of size 8 at 0x60300003a050 thread T0
    #0 0x7f5760d27db1 in std::__shared_ptr<cvc5::internal::NodeTemplate<true>, (__gnu_cxx::_Lock_policy)2>::get() const (/root/smt/cvc5/build/src/libcvc5.so.1+0x1c24db1)
    #1 0x7f5760d27dc0 in std::__shared_ptr_access<cvc5::internal::NodeTemplate<true>, (__gnu_cxx::_Lock_policy)2, false, false>::_M_get() const (/root/smt/cvc5/build/src/libcvc5.so.1+0x1c24dc0)
    #2 0x7f5760d27dd0 in std::__shared_ptr_access<cvc5::internal::NodeTemplate<true>, (__gnu_cxx::_Lock_policy)2, false, false>::operator->() const (/root/smt/cvc5/build/src/libcvc5.so.1+0x1c24dd0)
......
SUMMARY: AddressSanitizer: heap-buffer-overflow (/root/smt/cvc5/build/src/libcvc5.so.1+0x1c24db1) in std::__shared_ptr<cvc5::internal::NodeTemplate<true>, (__gnu_cxx::_Lock_policy)2>::get() const
......
```

**Comment by aniemetz** [comment]
Related to #9676, fixed by #9684.
